### ISSUE TITLE
Spotify User Login

### ISSUE THREAD

**Issue by JossySola** [Mohit-Gaur/Jammify#55]
Hi Mohit, I was just using your Web App and I was wondering how did you make it possible for any user to login and use the app?

I deployed this project recently and the users that are able to login and use the Web App need to be in my Spotify Allowed Users Dashboard... did you request to Spotify the quota extension?

Thank you so much for your help!

PS: I opened this issue as a way to contact you because there is no other way here in Github :(

**Comment by Mohit-Gaur** [comment]
Hi Solá, Thanks for reaching out!

I don't recall requesting a quota extension from Spotify. But I worked on this a couple years ago and things might have changed since then.

A quick search led me to [this](https://community.spotify.com/t5/Spotify-for-Developers/quot-User-not-registered-in-the-Developer-Dashboard-quot-on-user/td-p/5589350) and it seems that this was introduced recently.

**Comment by JossySola** [comment]
Hey, thank you so much for answering... yeah I guess it is something that wasn't a requirement at the time. Well, I'll have to request a Quota Extension and hope they accept it.

Thank you again!
